### PR TITLE
ffbs-mesh-vpn-parker: delete firewall rules for the prefix6 site config

### PR DESCRIPTION
**Pull request by grische**
As suggested [here](https://github.com/freifunk-gluon/community-packages/pull/142#issuecomment-2489694858) by @maurerle 

Can remove diff at https://github.com/ffbs/gluon-parker/commit/2e53380d2ff00f26d840e3f46bf12c9c76d9f15f#diff-70c0178fef0afe6aa581fdd24bcd19c5ad4f04874648698469f5f5896dc1b500L36

### CODE REVIEW

**Comment by SmithChart** [comment]
I do not understand how this is the same change. For me both matches look vastly different.

Also: The commit messages and commit reference different entries.
Please elaborate what this change does and how it makes the other rule obsolete.
While you are on it: Please extent the commit message to describe *why* this change is needed not only what it changes, as this is already part of the diff.

**Comment by maurerle** [comment]
Hi @SmithChart ,
the commit  chunk https://github.com/ffbs/gluon-parker/commit/2e53380d2ff00f26d840e3f46bf12c9c76d9f15f#diff-70c0178fef0afe6aa581fdd24bcd19c5ad4f04874648698469f5f5896dc1b500L36
Deletes the uci rule mesh_respondd_siteprefix from gluon, which is added in 400-respondd-firewall at gluon upgrades

The chunk in this PR adds a script to 401- respondd-firewall so directly after the above addition to delete any firewall rule called mesh_respondd_siteprefix

In both cases the role does not exist anymore after the upgrade.
Of course, deleting things directly after they were added seems weird, but it is better in this case as it reduces the differences to gluon required for Parker

**Comment by grische** [comment]
Also added the code comment as a git commit message.

**Review by SmithChart — APPROVED** [review]

**Comment by SmithChart** [comment]
Thanks for clarifying! It makes sense this way. I will drop the hunk from the key once this is merged.

**Comment by SmithChart** [comment]
FTR: Hunk dropped by force push.

**Pull request merged**
